Numpy Part-1

In [ ]:
import numpy as np

In [ ]:
l = [1,2,3,4]
a = np.array(l)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
b = np.array([[1,2],[3,4]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [ ]:
b = np.matrix(l)

In [ ]:
b

matrix([[1, 2, 3, 4]])

In [ ]:
np.asanyarray(0)

array(0)

In [ ]:
s = np.array(l)

In [ ]:
s

array([1, 2, 3, 4])

In [ ]:
c = s

In [ ]:
c

array([1, 2, 3, 4])

In [ ]:
c[0] = 100

In [ ]:
c

array([100,   2,   3,   4])

In [ ]:
d = np.copy(a)

In [ ]:
d

array([1, 2, 3, 4])

In [ ]:
a[2] = 200

In [ ]:
a

array([  1,   2, 200,   4])

In [ ]:
d

array([1, 2, 3, 4])

In [ ]:
np.fromfunction(lambda i,j : i==j , (3,3)) #here (3,3) is a 3x3 matrix

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [ ]:
np.fromfunction(lambda i,j : i==j ,(2,2)) #here (2,2) is a 2x2 matrix

array([[ True, False],
       [False,  True]])

In [ ]:
np.fromfunction(lambda i,j : i*j ,(2,2)) #here (2,2) is a 2x2 matrix

array([[0., 0.],
       [0., 1.]])

In [ ]:
iterable = (i*i for i in range(5))

In [ ]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [ ]:
np.fromstring('234 234', sep =' ')

array([234., 234.])

In [ ]:
np.fromstring('4,5', sep =',')

array([4., 5.])

In [ ]:
l

[1, 2, 3, 4]

In [ ]:
a = np.array(l)

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.ndim

1

In [ ]:
a2 = np.array([[1,2],[2,3],[3,4]])

In [ ]:
a2.ndim

2

In [ ]:
a.size

4

In [ ]:
a2.size

6

In [ ]:
a.shape

(4,)

In [ ]:
a.dtype

dtype('int64')

In [ ]:
a2.shape

(3, 2)

In [ ]:
a2.dtype

dtype('int64')

In [ ]:
a22 = np.array([[1.2,2.3],[2.3,4.5]])

In [ ]:
a22.dtype

dtype('float64')

In [ ]:
range(5)

range(0, 5)

In [ ]:
list(range(5))

[0, 1, 2, 3, 4]

In [ ]:
import numpy as np

In [ ]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [ ]:
np.arange(2.3,5.6,.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [ ]:
list(np.arange(2.3,5.6,.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [ ]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.zeros((3,4,2)) #4 rows and 2 columns and 3 matrix

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [ ]:
a1 = np.zeros((3,4,2,3))

In [ ]:
a1

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [ ]:
a1.ndim

4

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
on = np.ones((2,3,2))

In [ ]:
on+5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [ ]:
np.empty((3,6))

array([[5.03656385e-310, 0.00000000e+000, 6.60924995e-310,
        6.60924995e-310, 6.60924995e-310, 6.60924995e-310],
       [6.60924995e-310, 6.60924995e-310, 6.60924995e-310,
        6.60924995e-310, 6.60924995e-310, 6.60924995e-310],
       [6.60924995e-310, 6.60924995e-310, 6.60924995e-310,
        6.60924995e-310, 6.60924995e-310, 6.60924995e-310]])

In [ ]:
np.eye(4) # 4 rows and put 1 in a diagonal place

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.logspace(2,5,10, base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [ ]:
arr = np.random.randn(3,4)

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame(arr)

0         1         2         3
0 -0.280987 -0.353798 -0.899259 -0.968211
1 -1.396102  1.828090 -1.487515  1.356629
2 -0.020474  1.036799 -1.680767  0.573783

In [ ]:
np.random.randint(1,110,(3,4))

array([[109, 102, 108, 102],
       [103,  66,  41,  22],
       [ 90,  75,  79,  28]])

In [ ]:
z = np.random.randint(1,110,(300,400))

In [ ]:
pd.DataFrame(z)

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     15   80   58   13   22    8   59    7   74   74  ...   97  106    8   
1     53   32   40   48   20   62   70   45  108   42  ...   43   47   23   
2     47   15   16   70   51   30   45   34   70   89  ...   72   41   82   
3     21  100  100   12  106   81   60    8   77    8  ...   13   21   65   
4     29   25   11   75   95   12    6  104   49   74  ...   94   96   86   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   92   87   10   57  103    1   23   27  104   51  ...   30   46   51   
296   34   11   84   66   34   88   66   27   63   53  ...   43    4   33   
297    6   57   53    6   82   21   78   68   41   27  ...   61   37   83   
298   90   91   91   24   99   91   56   60   87   88  ...   79  109   95   
299   86   67   73   47   92   24   86   97   47   48  ...   45   75  103   

     393  394  395  396  397  398  399  
0     57   74  101    2   28   56   97  
1     41   89   35   82   73   94   58  
2     82  100  105   86   43   47   99  
3     19   52  106    3    8   31   72  
4     91   19   52   40   84   14  100  
..   ...  ...  ...  ...  ...  ...  ...  
295   59   86   24   28   53   96   40  
296   55   48   83   95   83    4   56  
297   98   67   81   40   67   13   91  
298   72   43    4   88   34   89   31  
299   32   29   33   15   74   89   53  

[300 rows x 400 columns]

In [ ]:
pd.DataFrame(z).to_csv("test")

In [ ]:
a = np.random.rand(3,4)

In [ ]:
a

array([[0.87247237, 0.47107658, 0.14287139, 0.46761976],
       [0.19352586, 0.45576802, 0.39311944, 0.67370149],
       [0.50741788, 0.05052152, 0.01067019, 0.19842996]])

In [ ]:
a.reshape(6,-1)

array([[0.87247237, 0.47107658],
       [0.14287139, 0.46761976],
       [0.19352586, 0.45576802],
       [0.39311944, 0.67370149],
       [0.50741788, 0.05052152],
       [0.01067019, 0.19842996]])

In [ ]:
a[0][1]

0.4710765817178123

In [ ]:
a[2:5,1]

array([0.05052152])

In [ ]:
a

array([[0.87247237, 0.47107658, 0.14287139, 0.46761976],
       [0.19352586, 0.45576802, 0.39311944, 0.67370149],
       [0.50741788, 0.05052152, 0.01067019, 0.19842996]])

In [ ]:
a>0.20

array([[ True,  True, False,  True],
       [False,  True,  True,  True],
       [ True, False, False, False]])

In [ ]:
a[2:4, [1,2]] #here start from row 2 and end with 3 , [1,2] is column

array([[0.05052152, 0.01067019]])

In [ ]:
a[0][0] = 5000

In [ ]:
a

array([[5.00000000e+03, 4.71076582e-01, 1.42871388e-01, 4.67619759e-01],
       [1.93525859e-01, 4.55768019e-01, 3.93119445e-01, 6.73701488e-01],
       [5.07417878e-01, 5.05215182e-02, 1.06701884e-02, 1.98429964e-01]])

In [ ]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))

In [ ]:
arr1+arr2

array([[2, 2, 2],
       [3, 3, 4],
       [4, 2, 2]])

In [ ]:
arr1/arr2

array([[1. , 1. , 1. ],
       [2. , 0.5, 1. ],
       [1. , 1. , 1. ]])

In [ ]:
arr1*arr2

array([[1, 1, 1],
       [2, 2, 4],
       [4, 1, 1]])

In [ ]:
arr1@arr2 #matrix multiplication

array([[4, 4, 4],
       [7, 6, 6],
       [5, 5, 5]])

In [ ]:
arr1**2

array([[1, 1, 1],
       [4, 1, 4],
       [4, 1, 1]])

Numpy - Broadcasting

In [ ]:
arr = np.zeros((4,4))

In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
row = np.array([1,2,3,4])

In [ ]:
arr + row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
row.T

array([1, 2, 3, 4])

In [ ]:
col = np.array([[1,2,3,4]])

In [ ]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
arr1 = np.random.randint(1,4,(3,4))

In [ ]:
arr1

array([[1, 2, 3, 2],
       [1, 3, 2, 1],
       [2, 3, 1, 1]])

In [ ]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.73205081, 1.41421356],
       [1.        , 1.73205081, 1.41421356, 1.        ],
       [1.41421356, 1.73205081, 1.        , 1.        ]])

In [ ]:
np.log10(arr1)

array([[0.        , 0.30103   , 0.47712125, 0.30103   ],
       [0.        , 0.47712125, 0.30103   , 0.        ],
       [0.30103   , 0.47712125, 0.        , 0.        ]])