Numpy Part-2

In [ ]:
#numpy array manipulation

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(1,10,(3,4))

In [ ]:
a

array([[2, 9, 5, 2],
       [3, 1, 3, 2],
       [9, 8, 1, 5]])

In [ ]:
a.reshape(6,2)

array([[2, 9],
       [5, 2],
       [3, 1],
       [3, 2],
       [9, 8],
       [1, 5]])

In [ ]:
a.reshape(2,6)

array([[2, 9, 5, 2, 3, 1],
       [3, 2, 9, 8, 1, 5]])

In [ ]:
a.T

array([[2, 3, 9],
       [9, 1, 8],
       [5, 3, 1],
       [2, 2, 5]])

In [ ]:
a.flatten()

array([2, 9, 5, 2, 3, 1, 3, 2, 9, 8, 1, 5])

In [ ]:
a1 = np.array([1,2,3,4])

In [ ]:
a1.ndim

1

In [ ]:
np.expand_dims(a1,axis=1)

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
np.expand_dims(a1,axis=0)

array([[1, 2, 3, 4]])

In [ ]:
np.squeeze(a)

array([[2, 9, 5, 2],
       [3, 1, 3, 2],
       [9, 8, 1, 5]])

In [ ]:
data = np.array([[1],[2],[3]])

In [ ]:
data

array([[1],
       [2],
       [3]])

In [ ]:
np.squeeze(data) #squeeze removes a dimension wof an array whose size is one

array([1, 2, 3])

In [ ]:
np.repeat(a,3)

array([2, 2, 2, 9, 9, 9, 5, 5, 5, 2, 2, 2, 3, 3, 3, 1, 1, 1, 3, 3, 3, 2,
       2, 2, 9, 9, 9, 8, 8, 8, 1, 1, 1, 5, 5, 5])

In [ ]:
np.roll(a1,2) #it shift the data

array([3, 4, 1, 2])

In [ ]:
np.roll(a1,3)

array([2, 3, 4, 1])

In [ ]:
np.diag(a1)

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
#Numpy Binary Operators

In [ ]:
a1 = np.random.randint(1,10,(3,4))

In [ ]:
a2 = np.random.randint(1,10,(3,4))

In [ ]:
a1+a2

array([[13, 17, 18, 12],
       [11,  6, 14, 14],
       [14,  9,  9, 14]])

In [ ]:
a1*a2

array([[36, 72, 81, 35],
       [24,  9, 49, 49],
       [45, 18, 18, 48]])

In [ ]:
~a1

array([[-10, -10, -10,  -8],
       [ -9,  -4,  -8,  -8],
       [ -6,  -4,  -7,  -7]])

In [ ]:
a1|a2

array([[13,  9,  9,  7],
       [11,  3,  7,  7],
       [13,  7,  7, 14]])

In [ ]:
a1&a2

array([[0, 8, 9, 5],
       [0, 3, 7, 7],
       [1, 2, 2, 0]])

In [ ]:
#Numpy string functions

In [ ]:
arr = np.array(["kirti","singh"])

In [ ]:
np.char.upper(arr)

array(['KIRTI', 'SINGH'], dtype='<U5')

In [ ]:
np.char.title(arr)

array(['Kirti', 'Singh'], dtype='<U5')

In [ ]:
np.char.capitalize(arr)

array(['Kirti', 'Singh'], dtype='<U5')

In [ ]:
#numpy mathe,matics functions

In [ ]:
a1

array([[9, 9, 9, 7],
       [8, 3, 7, 7],
       [5, 3, 6, 6]])

In [ ]:
np.sin(a1)

array([[ 0.41211849,  0.41211849,  0.41211849,  0.6569866 ],
       [ 0.98935825,  0.14112001,  0.6569866 ,  0.6569866 ],
       [-0.95892427,  0.14112001, -0.2794155 , -0.2794155 ]])

In [ ]:
np.cos(a1)

array([[-0.91113026, -0.91113026, -0.91113026,  0.75390225],
       [-0.14550003, -0.9899925 ,  0.75390225,  0.75390225],
       [ 0.28366219, -0.9899925 ,  0.96017029,  0.96017029]])

In [ ]:
np.tan(a1)

array([[-0.45231566, -0.45231566, -0.45231566,  0.87144798],
       [-6.79971146, -0.14254654,  0.87144798,  0.87144798],
       [-3.38051501, -0.14254654, -0.29100619, -0.29100619]])

In [ ]:
np.tanh(a1)

array([[0.99999997, 0.99999997, 0.99999997, 0.99999834],
       [0.99999977, 0.99505475, 0.99999834, 0.99999834],
       [0.9999092 , 0.99505475, 0.99998771, 0.99998771]])

In [ ]:
np.exp(a1)

array([[8103.08392758, 8103.08392758, 8103.08392758, 1096.63315843],
       [2980.95798704,   20.08553692, 1096.63315843, 1096.63315843],
       [ 148.4131591 ,   20.08553692,  403.42879349,  403.42879349]])

In [ ]:
np.sqrt(a1)

array([[3.        , 3.        , 3.        , 2.64575131],
       [2.82842712, 1.73205081, 2.64575131, 2.64575131],
       [2.23606798, 1.73205081, 2.44948974, 2.44948974]])

In [ ]:
np.power(a1,2)

array([[81, 81, 81, 49],
       [64,  9, 49, 49],
       [25,  9, 36, 36]])

In [ ]:
np.mean(a1)

6.583333333333333

In [ ]:
np.median(a1)

7.0

In [ ]:
np.std(a1)

2.0190069065976197

In [ ]:
np.min(a1)

3

In [ ]:
np.max(a1)

9