Numpy Part 3

In [ ]:
#Sort, Search & Counting Functions

In [ ]:
import numpy as np

In [ ]:
a = np.array([4,2,5,6,4,2,6,7,8])

In [ ]:
a

array([4, 2, 5, 6, 4, 2, 6, 7, 8])

In [ ]:
np.sort(a)

array([2, 2, 4, 4, 5, 6, 6, 7, 8])

In [ ]:
np.searchsorted(a,4)

2

In [ ]:
a1 = np.array([0,345,454,0,0,0,0,0])

In [ ]:
np.count_nonzero(a1)

2

In [ ]:
a

array([4, 2, 5, 6, 4, 2, 6, 7, 8])

In [ ]:
np.where(a>6) #print index for the given condition

(array([7, 8]),)

In [ ]:
np.extract(a>6,a) #print the value

array([7, 8])

In [ ]:
#numpy byte sampling

In [ ]:
a.byteswap()

array([288230376151711744, 144115188075855872, 360287970189639680,
       432345564227567616, 288230376151711744, 144115188075855872,
       432345564227567616, 504403158265495552, 576460752303423488])

In [ ]:
#numpy copies & views

In [ ]:
a2 = np.copy(a)

In [ ]:
a2

array([4, 2, 5, 6, 4, 2, 6, 7, 8])

In [ ]:
b = a.view() # b=a

In [ ]:
b

array([4, 2, 5, 6, 4, 2, 6, 7, 8])

In [ ]:
#numpy matrix library

In [ ]:
import numpy.matlib as nm

In [ ]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [ ]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [ ]:
#numpy-linear algebra

In [ ]:
a1 = np.random.randint([[2,3],[4,5]])

In [ ]:
a2 = np.random.randint([[5,3],[2,5]])

In [ ]:
np.dot(a1,a2)

array([[ 0,  6],
       [ 9, 15]])

In [ ]:
a1@a2

array([[ 0,  6],
       [ 9, 15]])